name: Trivy Image Scan

on:
  workflow_run:
    workflows: ["Code Build"]
    types:
      - completed
  push:
    branches:
      - main

jobs:
  build:
    name: Docker Image Scan
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull the Docker image
        run: docker pull codewithmuh/react-aws-eks-github-actions:latest

      - name: Trivy image scan
        run: |
          docker run --rm -v $(pwd):/app aquasec/trivy codewithmuh/react-aws-eks-github-actions:latest
